modified Jenkinsfile

diff --git a/Nodejs_app/Jenkinsfile b/Nodejs_app/Jenkinsfile
--- a/Nodejs_app/Jenkinsfile
+++ b/Nodejs_app/Jenkinsfile
@@ -2,16 +2,14 @@ pipeline {
     agent any
 
     environment {
-        AWS_REGION = "us-east-1"
-        AWS_ACCOUNT_ID = "123456789012"
-        ECR_REPO = "nodejs-demo"
+        APP_NAME = "nodejs-app"
         IMAGE_TAG = "${BUILD_NUMBER}"
     }
 
     stages {
         stage('Checkout') {
             steps {
-                git branch: 'main', url: 'https://github.com/YOUR_USERNAME/YOUR_REPO.git'
+                git branch: 'master', url: 'https://github.com/vasutkar-0/Nodejs_Sample_Project.git'
             }
         }
 
@@ -23,50 +21,34 @@ pipeline {
 
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t $ECR_REPO:$IMAGE_TAG .'
+                sh "docker build -t ${APP_NAME}:${IMAGE_TAG} ."
             }
         }
 
-        stage('Login to ECR') {
+        stage('Deploy on Jenkins Server') {
             steps {
-                sh '''
-                aws ecr get-login-password --region $AWS_REGION | \
-                docker login --username AWS \
-                --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
-                '''
-            }
-        }
+                sh """
+                # Stop previous container if exists
+                docker stop ${APP_NAME} || true
+                docker rm ${APP_NAME} || true
 
-        stage('Push to ECR') {
-            steps {
-                sh '''
-                docker tag $ECR_REPO:$IMAGE_TAG \
-                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
-
-                docker push \
-                $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
-                '''
-            }
-        }
-
-        stage('Deploy') {
-            steps {
-                sh '''
-                IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG
-
-                docker pull $IMAGE_URI
-
-                docker stop nodejs-app || true
-                docker rm nodejs-app || true
-
+                # Run new container
                 docker run -d \
-                  --name nodejs-app \
+                  --name ${APP_NAME} \
                   -p 3000:3000 \
                   --restart always \
-                  $IMAGE_URI
-                '''
+                  ${APP_NAME}:${IMAGE_TAG}
+                """
             }
         }
     }
-}
 
+    post {
+        success {
+            echo "Deployment successful! App running at http://172.25.3.110/:3000"
+        }
+        failure {
+            echo "Pipeline failed!"
+        }
+    }
+}
